FORMAT: 1A
HOST: http://publicapi.payments.service.gov.uk/

# GOV.UK Pay Telephone Payments reporting

## Document status

| Date | Author | Comment |
|------|--------|---------|
| 4/7/19 | David Heath | Mark `name_on_card` as optional  |
| 12/6/19 | David Heath | Add optional telephone number to notification payload |
| 12/6/19 | David Heath | Add notes of decisions made 27/3 (reference, description and date semantics) |
| 5/6/19 | David Heath | return GOV.UK Pay status from notification endpoint, changes to `payment_outcome` structure. Idempotency based on `provider_id`. Add 422 HTTP response code. |
| 24/1/19 | David Heath | first draft |

## Purpose and intended audience

this document describes requirements for the API integration between ECKOH and GOV.UK Pay.

## Security requirements

The integration with GOV.UK Pay will be via a new endpoint on the existing GOV.UK Pay Public API, and so this document should be read in conjunction with our [public API documentation](https://docs.payments.service.gov.uk/). 

In particular the [Security](https://docs.payments.service.gov.uk/security/#security) section outlines overal security requirements including secure handling of API tokens and PCI DSS compliance.

## Overview of architectural components

| Component  | Description |
|------------|-------------|
| Worldpay   | payment gateway used to process payments on behalf of NHS BSA |
| ECKOH      | Payments IVR and integration with Worldpay |
| KCOM       | Call centre IVR |
| GOV.UK Pay | integrated payment processing |
| NHS BSA    | delivering the end-user service |

For each completed telephone payment transaction ECKOH will send a [payment notification](#reference/0/notifications) to GOV.UK Pay satisfying the following requirements:

1. Encryption - Transmitted via HTTPS protocol with TLS1.2+ encryption
1. Timeliness - Transmitted as soon as possible after the event occurs. Ideally in a few seconds or less.
1. Authenticity - using [OAuth 2 bearer token](https://docs.payments.service.gov.uk/api_reference/#authentication)
1. Retries - If the notification is not acknowledged via a successful 200 response then you must retry notification delivery for up to 72 hours.
1. Configuration - API tokens are issued via GOV.UK Pay's selfservice interface, NHSBSA will have access to this interface, and may choose to grant access to ECKOH staff by issuing user accounts.

## Technical decisions agreed

1. GOV.UK Pay does not require an HMAC signature for authentication. OAuth bearer token is sufficient
2. Retries will be done individually on a per-payment basis
3. `processor_id` will be populated with the 23 digit `unique_reference_number` generated by ECKOH
4. Worldpay Notifications - Eckoh do not expect to receive notifications from Worldpay; therefore worldpay notifications will be [directed to GOV.UK Pay’s endpoint](https://docs.payments.service.gov.uk/switching_to_live/set_up_a_live_worldpay_account/).
5. `auth_code` corresponds to the `AuthorisationId` in the [Worldpay auth response](http://support.worldpay.com/support/kb/gg/corporate-gateway-guide/content/directintegration/paymentrequests.htm)
6. Payloads will be in JSON format with UTF8 character encoding
1. The `reference` field is intended as the primary way for end-users and NHS BSA support staff to identify a payment, and will be used for online NHS BSA payments. NHS BSA will set a reference for each payment which will be passed to ECKOH and on to GOV.UK Pay
2. The `description` field is intended as a human-readable description of the payment. NHS BSA will set a description for each payment which is passed to ECKOH and on to GOV.UK Pay.
3. Transaction date - GOV.UK Pay will accept two optional fields with the notification payload:
      - `created_date` - date/time when the payment was initiated by NHS BSA
      - `authorised_date` - date/time when the payment was authorised by Worldpay

## Points still awaiting confirmation

1. [NHS BSA gateway configuration](#/introduction/nhs-bsa-gateway-configuration) - we recommend Option 1 (Separate accounts)

## Features of GOV.UK Pay not available for telephone payments

1. **Email notifications** GOV.UK Pay offers a feature to send email notifications about payments and refunds to users. For telephone payments this will not be possible unless we are provided with an email address for the user. If the NHS BSA wishes to use this feature they would need to pass an email address to ECKOH who would then propagate it to GOV.UK Pay via the `email_address` field.

## NHS BSA Gateway configuration

NHS BSA will process payments via two channels:

1. online using GOV.UK Pay
2. by telephone using ECKOH, with payment information reported to GOV.UK Pay

There are several options for [structuring accounts](https://docs.payments.service.gov.uk/account_structure/#type-1-gov-uk-pay-separate-psp-separate).

### Option 1 - separate pay services

| Channel  | GOV.UK Pay Service | Worldpay merchant code |
|----------|--------------------|------------------------|
| Online   | A                  | MC1                    |
| Telphone | B                  | MC2                    |

Each channel uses a separate pay service and a separate worldpay merchant code.

The advantage of this approach is that it allows separate access control
for online transaction data and telephone payment transaction data.

Separate GOV.UK Pay API tokens will be required for each Service.

Transactions would be stored in separate 'ledgers' in GOV.UK Pay.

### Option 2 - single Pay service

| Channel  | GOV.UK Pay Service | Worldpay merchant code |
|----------|--------------------|------------------------|
| Online   | A                  | MC1                    |
| Telphone | A                  | MC1                    |

GOV.UK Pay manages access controls on a per-service basis, so in this scenario users with access to Pay's selfservice interface would have access to payments via both channels.

Furthermore, API tokens issued here provide read and write access to transactions from both channels.

### Assumption

Our assumption is that NHS BSA will use Option 1. 

In both scenarios, **notifications from Worldpay for BOTH online and telephone payments MUST be directed to GOV.UK Pay [as per the instructions](https://docs.payments.service.gov.uk/switching_to_live/set_up_a_live_worldpay_account/#set-up-merchant-channel)**.

ECKOH have indicated that they do not need to receive worldpay notifications.

### Configuration of GOV.UK Pay gateway accounts

Full details of the configuration process are covered in our documentation:

https://docs.payments.service.gov.uk/switching_to_live/set_up_a_live_worldpay_account/

## Example payment flow

1. End user calls call centre operated by KCOM, and requests a service which requires payment
2. Call is transferred to ECKOH who receive the payment details and process the payment with Worldpay. Payment will be AUTHORISED and if successful, CAPTURE requested.
3. ECKOH will make a [Payment Notification] call to GOV.UK Pay, containing transaction details and the status of the payment.
4. GOV.UK Pay records the transaction details
5. GOV.UK Pay receives a CAPTURED notification from Worldpay

## Refunds

NHS BSA will be able to issue refunds of telephone payments via the GOV.UK Pay selfservice interface or [GOV.UK Pay API](https://docs.payments.service.gov.uk/refunding_payments/#refunding-with-the-gov-uk-pay-api).

# Data Structures

## Payment Notification

+ amount: 12000 (number, required) - the amount in pence
+ reference: `MRPC12345` (string, required) - a reference code determined by you, max 255 chars, this may have been provided by the NHS service when they initiated the telephone payment 
+ description: `New passport application` (string, required) - human readable description, this may have been provided by the NHS service when they initiated the telephone payment 
+ created_date: `2018-02-21T16:04:25Z` (string) - date/time when the payment was initiated by NHS BSA - ISO8601 including timezone
+ authorised_date: `2018-02-21T16:05:33Z` (string) - date/time when the payment was authorised by Worldpay - ISO8601 including timezone
+ processor_id: `183f2j8923j8` (string, required) - Unique Eckoh Reference generated by Eckoh
+ provider_id: `17498-8412u9-1273891239` (string, required) - WorldPay `orderCode`
+ auth_code: `666` (string, optional) - [Worldpay `AuthorisationId`](http://support.worldpay.com/support/kb/gg/corporate-gateway-guide/content/directintegration/paymentrequests.htm#ExampleAuth)
+ payment_outcome (Payment Notification Outcome) (required)
+ card_type (enum, required)
    + `master-card`
    + `visa`
    + `maestro`
    + `diners-club`
    + `american-express`
+ name_on_card: `Jane Doe` (string, optional)
+ `email_address`: `jane_doe@example.com` (string, optional)
+ card_expiry: `02/19` (string, required) - card expiry date as MM/YY
+ last_four_digits: `1234` (string, required)
+ first_six_digits: `654321` (string, required)
+ telephone_number: `+447700900796` (string, optional) - caller's phone number (stored as metadata field in GOV.UK Pay)

## Payment Notification Outcome

+ status (enum, required)
   + `success` - payment has been authorised and sent for capture (maps to [GOV.UK Pay state](https://docs.payments.service.gov.uk/api_reference/#payment-status-lifecycle) `success`)
   + `failed` - error processing payment (code `P0050`) or authorisation declined (code `P0010`) or cancelled by user (code `P0030`)
+ code (enum) - explanatory error code. For status `failed` a code is required
   + `P0010` - Payment rejected due to payment method selected, or payment information entered. For example, failed fraud check, a 3D Secure authentication failure, or the user has insufficient funds in account.
   + `P0030` - Payment cancelled by user (not sure if this is applicable, but could be used eg. to indicate a call terminated before completion)
   + `P0050` - Error processing payment error
+ supplemental (object, optional) - optional additional details about the error or failure. These fields are stored as [custom metadata](https://docs.payments.service.gov.uk/optional_features/custom_metadata/#adding-custom-metadata) in GOV.UK Pay, so they would be visible in the selfservice interface and reporting
   + `error_code`: `ECKOH01234` (string) - a code indicating the error reason. This will be persisted in a GOV.UK Pay custom metadata field named `notification_error_code`.
   + `error_message`: `textual message describing error code` (string) - human readable message describing the error. This will be persisted in a GOV.UK Pay custom metadata field named `notification_error_message`

## Persisted Notification (Payment Notification)

+ payment_id: `hu20sqlact5260q2nanm0q8u93` (string, required) unique payment ID generated by GOV.UK Pay
+ `state` (required) - https://govukpay-api-browser.cloudapps.digital/#tocspaymentstate
    + status: `success` (string, required) - the [GOV.UK Pay state](https://docs.payments.service.gov.uk/api_reference/#payment-status-lifecycle) that has been recorded,
    + finished: `true` (boolean, required) - indicating whether this is a terminal state
    + message (string) - human readable description of the error condition based on [GOV.UK Pay's status codes `P00xx`](https://docs.payments.service.gov.uk/api_reference/#errors-caused-by-payment-statuses)
    + code: `P0010` (string) - [GOV.UK Pay error code](https://docs.payments.service.gov.uk/api_reference/#errors-caused-by-payment-statuses) indicating the error condition.

## Error

+ field: `amount` (string, optional) - may specifiy which field is invalid
+ code: `P0102` (string, required) - as per https://docs.payments.service.gov.uk/api_reference/#http-status-codes
+ description: `Invalid attribute value: amount. Must be less than or equal to 10000000` (string, required) - human readable description of the error

# Notifications [/v1/payment_notification]

### Payment notification [POST]

When we receive this call we expect the payment to be in one of three statuses, indicated in the `payment_outcome`:

1. status `success` - payment has been authorised successfully and sent for capture
1. status `failed`, code `P0050` - error processing payment, further details in `supplemental`
1. status `failed`, code `P0010` - authorisation declined

Retries will be processed idempotently, keyed by `provider_id`.

GOV.UK Pay will respond with either a 200 or 201 status code to indicate a successfully received transaction.

* 201 indicates a transaction not seen before
* 200 indicates a transaction already seen (`provider_id` seen before)

On receipt of a response outside of the 200-299 range, the notification MUST be retried.

Retries must continue at a maximum frequency of once per hour for up to 72 hours.

Other response codes possible are:

| Code | Meaning |
|------|---------|
| 200  | OK      |
| 201  | Created | 
| 401  | Unauthorised - invalid API token |
| 400  | Bad request - unparsable, missing required fields, or invalid fields. Details are in the response body json. |
| 422  | Unprocessable entity - unparsable, missing required fields, or invalid fields. Details are in the response body json. |
| 5xx  | Technical error. Request should be retried |

+ Request  (application/json)
    + Attributes (Payment Notification)
    
+ Response 200 (application/json)
    
    + Attributes (Persisted Notification)

+ Response 201 (application/json)
    
    + Attributes (Persisted Notification)

+ Response 401 (application/json)
    
    + Body - empty body
    
+ Response 400 (application/json)
    
    + Attributes (Error)
    
+ Response 422 (application/json)
    
    + Attributes (Error)